name: GitHub profile README generator
on:
  schedule: [{cron: "0 */4 * * *"}]
  push: {branches: ["main"]}
concurrency:
  group: metrics
jobs:
  resources:
    name: Generate resources
    runs-on: ubuntu-latest
    steps:
      - name: Update stats.svg
        uses: lowlighter/metrics@latest
        with:
          user: kip93
          token: ${{ secrets.TOKEN }}
          output_action: commit
          committer_branch: main
          committer_message: Update ${filename} - [GitHub Action]
          config_timezone: Etc/UTC

          template: classic
          config_display: large
          filename: stats.svg
          config_output: svg

          base: "activity, community, repositories"
          plugin_lines: yes
          plugin_traffic: yes
          extras_css: |
            * { font-size: 15px; }
            h2 { margin: 2px 5px 6px !important; }

      - name: Update languages.svg
        uses: lowlighter/metrics@latest
        with:
          user: kip93
          token: ${{ secrets.TOKEN }}
          output_action: commit
          committer_branch: main
          committer_message: Update ${filename} - [GitHub Action]
          config_timezone: Etc/UTC

          template: classic
          config_display: large
          filename: languages.svg
          config_output: svg

          base: ""
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_categories: data, markup, programming, prose  # all
          plugin_languages_details: percentage
          plugin_languages_limit: 8  # max
          plugin_languages_threshold: 0%
          extras_css: |
            * { font-size: 16px; }
            h2, h3 { margin: 0px; opacity: 0%; width: 0px; height: 0px; }
            .row { justify-content: center; }
            .row section { flex: unset !important; width: 232px }
            .field svg { margin: 0px 8px 0 -4px; }

      - name: Update achievements.svg
        uses: lowlighter/metrics@latest
        with:
          user: kip93
          token: ${{ secrets.TOKEN }}
          output_action: commit
          committer_branch: main
          committer_message: Update ${filename} - [GitHub Action]
          config_timezone: Etc/UTC

          template: classic
          config_display: large
          filename: achievements.svg
          config_output: svg

          base: ""
          plugin_achievements: yes
          plugin_achievements_threshold: B
          plugin_achievements_secrets: yes
          plugin_achievements_limit: 0  # all
          plugin_achievements_display: compact
          extras_css: |
            h2, h3 { margin: 0px; opacity: 0%; width: 0px; height: 0px; }

  readme:
    name: Generate README
    needs: [resources]
    runs-on: ubuntu-latest
    steps:
      - name: Update README.md
        uses: lowlighter/metrics@latest
        with:
          user: kip93
          token: ${{ secrets.TOKEN }}
          output_action: commit
          committer_branch: main
          committer_message: Update ${filename} - [GitHub Action]
          config_timezone: Etc/UTC

          template: markdown
          filename: README.md
          config_output: markdown

          markdown: https://raw.githubusercontent.com/kip93/kip93/main/TEMPLATE.md

          plugin_activity: yes
          plugin_activity_days: 0
          plugin_activity_limit: 4
          plugin_activity_visibility: public
          plugin_activity_filter: all
          plugin_activity_timestamps: yes
